# expose the NFS server to receive incomming traffic
kind: Service
apiVersion: v1
metadata:
  name: nfs-server
spec:
  # set a static IP address
  clusterIP: 10.109.131.215
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server
