apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # using a fixed IP address
    #server: 10.109.131.215
    # using a dynamic service name
    server: nfs-server.default.svc.cluster.local
    path: "/"
