# Create a simple hostPath PV to provision your NFS server
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nfs-pv-provisioning-demo
spec:
  storageClassName: local
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  #persistentVolumeReclaimPolicy: Retain 
  hostPath:
    path: /mnt/disk
