apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nfs-server
  labels: 
    role: nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs
  template:
    metadata:
      labels:
        role: nfs
    spec:
      containers:
      - name: nfs-server
        image: k8s.gcr.io/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: mypvc
      #nodeSelector:
      #  nodeType: master
      # Mount the volume provisioned by the nfs-pvc-provisioning claim into the /exports folder of the server through the volume name
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: nfs-pvc-provisioning-demo
