kind: PersistentVolume
apiVersion: v1
metadata:
  name: nfs-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  hostPath:
    path: /volume
  #nfs: 
  #  # FIXME: use the NFS server IP to update (kubectl describe services nfs-server)
  #  server: 10.244.1.4
  #  path: "/"
