apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-provisioning 
spec:
  storageClassName: manual   # the Kubernetes control plane looks for a PersistentVolume that satisfies the claim’s requirements. If the control plane finds a suitable PersistentVolume with the same StorageClass, it binds the claim to the volume.
  accessModes:
  - ReadWriteOnce      
  resources:
     requests:
       storage: 1Gi
