apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-provisioning-demo
spec:
  storageClassName: local   # the Kubernetes control plane looks for a PersistentVolume that satisfies the claim’s requirements. If the control plane finds a suitable PersistentVolume with the same StorageClass, it binds the claim to the volume.
  accessModes:
  - ReadWriteOnce      
  resources:
     requests:
       storage: 10Gi
