apiVersion: v1
kind: ConfigMap
metadata:
  name: tensorflow-cluster-config
data:
  ps: 
     "tensorflow-ps-service.default.svc.cluster.local:2222"
  worker:
     "tensorflow-wk-service0.default.svc.cluster.local:2222,tensorflow-wk-service1.default.svc.cluster.local:2222"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: tensorflow-ps-rc
spec:
  replicas: 1
  selector:
    name: tensorflow-ps
  template:
    metadata:
      labels:
        name: tensorflow-ps
        role: ps
    spec:  
      containers:
      - name: ps
        image: gcr.io/tensorflow/tensorflow:latest
        ports:
        - containerPort: 2222
        env:
        - name: PS_KEY
          valueFrom:
            configMapKeyRef:
              name: tensorflow-cluster-config
              key: ps
        - name: WORKER_KEY
          valueFrom:
            configMapKeyRef:
              name: tensorflow-cluster-config
              key: worker
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /tfdata
          name: tfstorage001
      volumes:
      - name: tfstorage001
        persistentVolumeClaim:
          claimName: nfs
---
apiVersion: v1
kind: Service 
metadata:
  labels:
    name: tensorflow-ps
    role: service
  name: tensorflow-ps-service
spec:
  ports:
    - port: 2222
      targetPort: 2222
  selector:
    name: tensorflow-ps
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: tensorflow-worker0-rc
spec:
  replicas: 1
  selector:
    name: tensorflow-worker0
  template:
    metadata:
      labels:
        name: tensorflow-worker0
        role: worker
    spec:  
      containers:
      - name: worker
        image: gcr.io/tensorflow/tensorflow:latest
        ports:
        - containerPort: 2222
        env:
        - name: PS_KEY
          valueFrom:
            configMapKeyRef:
              name: tensorflow-cluster-config
              key: ps
        - name: WORKER_KEY
          valueFrom:
            configMapKeyRef:
              name: tensorflow-cluster-config
              key: worker
        securityContext:
          privileged: true
        #resources:
        #  requests:
        #    alpha.kubernetes.io/nvidia-gpu: 1
        #  limits:
        #    alpha.kubernetes.io/nvidia-gpu: 1
        volumeMounts:
        #- mountPath: /dev/nvidia0
        #  name: nvidia0
        #- mountPath: /dev/nvidiactl
        #  name: nvidiactl
        #- mountPath: /dev/nvidia-uvm
        #  name: nvidia-uvm
        - mountPath: /tfdata
          name: tfstorage001
        #- name: libcuda-so
        #  mountPath: /usr/lib/x86_64-linux-gnu
        #- name: cuda
        #  mountPath: /usr/local/cuda-8.0
      volumes:
      - name: tfstorage001
        persistentVolumeClaim:
          claimName: nfs
      #- hostPath:
      #    path: /dev/nvidia0
      #  name: nvidia0
      #- hostPath:
      #    path: /dev/nvidiactl
      #  name: nvidiactl
      #- hostPath:
      #    path: /dev/nvidia-uvm
      #  name: nvidia-uvm
      #- name: libcuda-so
      #  hostPath:
      #    path: /usr/lib/x86_64-linux-gnu
      #- name: cuda
      #  hostPath:
      #    path: /usr/local/cuda-8.0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: tensorflow-worker0
    role: service
  name: tensorflow-wk-service0
spec:
  ports:
    - port: 2222
      targetPort: 2222
  selector:
    name: tensorflow-worker0
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: tensorflow-worker1-rc
spec:
  replicas: 1
  selector:
    name: tensorflow-worker1
  template:
    metadata:
      labels:
        name: tensorflow-worker1
        role: worker
    spec:  
      containers:
      - name: worker
        image: gcr.io/tensorflow/tensorflow:latest
        ports:
        - containerPort: 2222
        env:
        - name: PS_KEY
          valueFrom:
            configMapKeyRef:
              name: tensorflow-cluster-config
              key: ps
        - name: WORKER_KEY
          valueFrom:
            configMapKeyRef:
              name: tensorflow-cluster-config
              key: worker
        securityContext:
          privileged: true
        #resources:
        #  requests:
        #    alpha.kubernetes.io/nvidia-gpu: 1
        #  limits:
        #    alpha.kubernetes.io/nvidia-gpu: 1
        volumeMounts:
        #- mountPath: /dev/nvidia0
        #  name: nvidia0
        #- mountPath: /dev/nvidiactl
        #  name: nvidiactl
        #- mountPath: /dev/nvidia-uvm
        #  name: nvidia-uvm
        - mountPath: /tfdata
          name: tfstorage001
        #- name: libcuda-so
        #  mountPath: /usr/lib/x86_64-linux-gnu
        #- name: cuda
        #  mountPath: /usr/local/cuda-8.0
      volumes:
      - name: tfstorage001
        persistentVolumeClaim:
          claimName: nfs
      #- hostPath:
      #    path: /dev/nvidia0
      #  name: nvidia0
      #- hostPath:
      #    path: /dev/nvidiactl
      #  name: nvidiactl
      #- hostPath:
      #    path: /dev/nvidia-uvm
      #  name: nvidia-uvm
      #- name: libcuda-so
      #  hostPath:
      #    path: /usr/lib/x86_64-linux-gnu
      #- name: cuda
      #  hostPath:
      #    path: /usr/local/cuda-8.0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: tensorflow-worker1
    role: service
  name: tensorflow-wk-service1
spec:
  ports:
    - port: 2222
      targetPort: 2222
  selector:
    name: tensorflow-worker1
