apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorflow-ps-rc
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tensorflow-ps
  template:
    metadata:
      labels:
        name: tensorflow-ps
        role: ps
    spec:  
      containers:
      - name: ps
        image: gcr.io/tensorflow/tensorflow:latest
        ports:
        - containerPort: 2222
        #env:
        #- name: PS_KEY
        #  valueFrom:
        #    configMapKeyRef:
        #      name: tensorflow-cluster-config
        #      key: ps
        #- name: WORKER_KEY
        #  valueFrom:
        #    configMapKeyRef:
        #      name: tensorflow-cluster-config
        #      key: worker
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /tfdata
          name: tfstorage001
      volumes:
      - name: tfstorage001
        persistentVolumeClaim:
          claimName: nfs
