#!/bin/bash
# script to install all the command tools you need to proper run a cluster with kubeadm

# first, make sure you are the root user with sudo su
sudo su

#
echo "Installing Docker"
apt-get update
apt-get install -y docker.io

#
echo "Install the configuration tools you need, kubeadm, kubectl, kubelet"
apt-get update && apt-get install -y apt-transport-https curl
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF
apt-get update
apt-get install -y kubelet kubeadm kubectl

#
echo "installing updates and upgrades"
apt-get update && apt-get upgrade
