#!/bin/bash
# script to start a cluster with kubeadm
# first, make sure you are the root user with sudo su
#sudo su

echo "Hi there! Soon you will be joining a Kubernetes cluster, have fun!"
# change next line in the future to initialize cluster form a config file
kubeadm join 143.129.83.140:6443 --token abcdef.0123456789abcdef --discovery-token-ca-cert-hash sha256:<hex_hash_code>
